# Generated by Django 3.1.7 on 2021-03-06 07:47

from django.db import migrations, models
import visual.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3, validators=[visual.models.month_validator])),
                ('social_media_follower', models.IntegerField()),
                ('website_visitors', models.IntegerField()),
            ],
        ),
    ]
