# Generated by Django 3.1.7 on 2021-03-06 10:44

from django.db import migrations, models
import visual.models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0002_auto_20210306_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3, validators=[visual.models.month_validator])),
                ('net_promoter_score', models.IntegerField(null=True)),
                ('net_new_customer', models.IntegerField(null=True)),
                ('num_of_customer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3, validators=[visual.models.month_validator])),
                ('num_of_employee', models.IntegerField(null=True)),
                ('num_of_open_position', models.IntegerField(null=True)),
                ('time_to_hire', models.IntegerField(null=True)),
                ('attrition', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3, validators=[visual.models.month_validator])),
                ('dev_freq', models.IntegerField(null=True)),
                ('est_accuracy', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('test_coverage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3, validators=[visual.models.month_validator])),
                ('sp_avg_reaction_time', models.IntegerField(null=True)),
                ('sp_avg_resolution_time', models.IntegerField(null=True)),
                ('customer_escalation', models.IntegerField(null=True)),
                ('availability', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('open_support_ticket', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3, validators=[visual.models.month_validator])),
                ('software_revenue', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('other_revenue', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('professional_service_revenue', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='marketing',
            name='lead_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
