version: '3'
services:
  django:
    build: ./dashboard
    volumes:
      - ./dashboard:/project
    ports:
      - 8081:8000

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dashboard/media:/usr/share/nginx/media
      - ./dashboard/static:/usr/share/nginx/static
    ports:
      - "80:8080"
  
